parameters:
    mongo_server:      mongodb://localhost:27017
    mongo_port:        ~
    mongo_name:        behat

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    node_bin:  /bin/node
    node_path: [/usr/lib/node:/usr/lib/node_modules:/root/node_modules]
