behat_browser_api_definitions:
    type:     rest
    resource: BehatBrowser\Bundle\CoreBundle\Controller\DefinitionsController
    name_prefix: behat_browser_api

behat_browser_api_features:
    type:     rest
    resource: BehatBrowser\Bundle\CoreBundle\Controller\FeaturesController
    name_prefix: behat_browser_api
#
#itsallagileAPIBundle_stories:
#    type:     rest
#    parent:   itsallagileAPIBundle_boards
#    resource: itsallagile\APIBundle\Controller\StoriesController
#    name_prefix: itsallagileAPIBundle_
#
#itsallagileAPIBundle_tickets:
#    type:     rest
#    parent:   itsallagileAPIBundle_stories
#    resource: itsallagile\APIBundle\Controller\TicketsController
#    name_prefix: itsallagileAPIBundle_
#
#
#itsallagileAPIBundle_messages:
#    type:     rest
#    parent:   itsallagileAPIBundle_boards
#    resource: itsallagile\APIBundle\Controller\MessagesController
#    name_prefix: itsallagileAPIBundle_
#
#
#itsallagileAPIBundle_auth:
#    type:     rest
#    resource: itsallagile\APIBundle\Controller\AuthController
#    name_prefix: itsallagileAPIBundle_
