parameters:
#    behat_browser_core.example.class: BehatBrowser\Bundle\CoreBundle\Example

services:
#    behat_browser_core.example:
#        class: %behat_browser_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
